DEFAULT_CATEGORIES = [
    "FOOD",
    "TRAVEL",
    "SHOPPING",
    "ELECTRONICS",
    "HEALTH",
    "UTILITIES",
    "ENTERTAINMENT",
    "SUBSCRIPTIONS",
    "EDUCATION",
    "TRANSPORT",
    "OTHER",
]
